workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
    scripts:
      - name: Build for iOS Simulator
        script: |
          xcodebuild \
            -project Keepsakes.xcodeproj \
            -scheme Keepsakes \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build
    artifacts:
      - build/Build/Products/**/*.app